"""Pydantic domain models: the shared contract layer."""

from callswarm.models.agents import AgentRequest, AgentRun, AgentSpec
from callswarm.models.approvals import Approval, SuppressionEntry, hash_phone
from callswarm.models.base import DomainModel, IdentifiedModel, JsonValue, new_id, utcnow
from callswarm.models.calls import (
    CallIntent,
    CallRecipient,
    CallRun,
    CallValueFactors,
    CompletionConfidence,
    RecipientResult,
)
from callswarm.models.enums import (
    ActivityEventType,
    AgentRequestStatus,
    AgentState,
    ApprovalStatus,
    ApprovalSubjectType,
    AttemptStatus,
    CallAuthorizationState,
    CallPattern,
    CallStatus,
    EvidenceStatus,
    Freshness,
    GapStatus,
    Importance,
    MissionStatus,
    RecipientStatus,
    RiskLevel,
    ScheduledJobStatus,
    SourceType,
    StrategyStatus,
    WebhookEventType,
)
from callswarm.models.events import ActivityEvent, ScheduledJob
from callswarm.models.evidence import EvidenceClaim, PlanComponent, PlanOption
from callswarm.models.mission import (
    AuthorityPolicy,
    CallBudget,
    ClarificationQuestion,
    ConstraintOperator,
    HardConstraint,
    Mission,
    MissionSpec,
    SoftPreference,
)
from callswarm.models.research import (
    CandidateEntity,
    ContactInfo,
    ExtractedClaim,
    InformationGap,
    Provenance,
    ResearchArtifact,
)
from callswarm.models.strategy import StrategyCandidate

__all__ = [
    "ActivityEvent",
    "ActivityEventType",
    "AgentRequest",
    "AgentRequestStatus",
    "AgentRun",
    "AgentSpec",
    "AgentState",
    "Approval",
    "ApprovalStatus",
    "ApprovalSubjectType",
    "AttemptStatus",
    "AuthorityPolicy",
    "CallAuthorizationState",
    "CallBudget",
    "CallIntent",
    "CallPattern",
    "CallRecipient",
    "CallRun",
    "CallStatus",
    "CallValueFactors",
    "CandidateEntity",
    "ClarificationQuestion",
    "CompletionConfidence",
    "ConstraintOperator",
    "ContactInfo",
    "DomainModel",
    "EvidenceClaim",
    "EvidenceStatus",
    "ExtractedClaim",
    "Freshness",
    "GapStatus",
    "HardConstraint",
    "IdentifiedModel",
    "Importance",
    "InformationGap",
    "JsonValue",
    "Mission",
    "MissionSpec",
    "MissionStatus",
    "PlanComponent",
    "PlanOption",
    "Provenance",
    "RecipientResult",
    "RecipientStatus",
    "ResearchArtifact",
    "RiskLevel",
    "ScheduledJob",
    "ScheduledJobStatus",
    "SoftPreference",
    "SourceType",
    "StrategyCandidate",
    "StrategyStatus",
    "SuppressionEntry",
    "WebhookEventType",
    "hash_phone",
    "new_id",
    "utcnow",
]
